<a href="https://colab.research.google.com/github/cmerino15/teach/blob/main/linear_algebra_classroom_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__'

In [ ]:
a3 = np.array([[1,2],[3,4]]) # access row using a3[0] and row-colm using a3[1,1]; add and mult component wise
a4 = np.array([[1,0],[0,1]])

In [ ]:
import tensorflow as tf  # needed for linalg module


In [ ]:
print(tf.add(a3,a4))

tf.Tensor(
[[2 2]
 [3 5]], shape=(2, 2), dtype=int64)


In [ ]:
tf.multiply(a3,a3) # mult STILL component wise

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[ 1,  4],
       [ 9, 16]])>

In [ ]:
print(np.matmul(a3,a3)) # numpy matrix-multiply function

[[ 7 10]
 [15 22]]


In [ ]:
import numpy.matlib as mtrx # using the matrix-library

In [ ]:
mtrx.matmul(a3,a3)

array([[ 7, 10],
       [15, 22]])

In [ ]:
# we might as well use matlib to define matrices faster however
A = mtrx.identity(2)
print(A)

[[1. 0.]
 [0. 1.]]


In [ ]:
B = mtrx.zeros((2,2), dtype = int) # or try mtrx.ones
B[0,0] = 1
B[0,1] = 2
B[1,0] = 3
B[1,1] = 4
print(B)

[[1 2]
 [3 4]]


In [ ]:
C = mtrx.eye(3)
print(C)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(B*B) # notice that if the matrices are created using the matlib then we can use * 

[[ 7 10]
 [15 22]]


In [ ]:
# treating the np.array a3 as a matrix using .linalg
print(mtrx.linalg.det(a3)) # notice the rounding error

-2.0000000000000004


In [ ]:
print(mtrx.linalg.det(B)) # notice the rounding error

-2.0000000000000004


In [ ]:
print(mtrx.linalg.inv(B)) # yet inverse is still calculated correctly ... same for a3

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
print(mtrx.linalg.eigvals(B))  # see eig example below for eigenvectors

[-0.37228132  5.37228132]


In [ ]:
print(mtrx.linalg.matrix_rank(B))

2


In [ ]:
print(mtrx.np.trace(B))

5


In [ ]:
print(mtrx.linalg.matrix_power(B, 3))

[[ 37  54]
 [ 81 118]]


In [ ]:
print(B**3) # reminder because the matrix was created using matlib

[[ 37  54]
 [ 81 118]]


In [ ]:
print(mtrx.linalg.eigh(B)) # for complex values or symmetric matrices (return left eigen vals and vectors)


(array([-0.85410197,  5.85410197]), matrix([[-0.85065081,  0.52573111],
        [ 0.52573111,  0.85065081]]))


In [ ]:
print(mtrx.linalg.eig(B)) # right eigen value and vectors compare to eigenvals function

(array([-0.37228132,  5.37228132]), matrix([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))


In [ ]:
import scipy

In [ ]:
print(B)
P, L, U = scipy.linalg.lu(B) # really this use P*A = L*U factorization
# print(scipy.linalg.lu(B))
print("-----")
print(P)
print(L)
print(U)

[[1 2]
 [3 4]]
-----
[[0. 1.]
 [1. 0.]]
[[1.         0.        ]
 [0.33333333 1.        ]]
[[3.         4.        ]
 [0.         0.66666667]]


In [ ]:
print(mtrx.matmul(L,U))

print(mtrx.matmul(P,B))

[[3. 4.]
 [1. 2.]]
[[3. 4.]
 [1. 2.]]


In [ ]:
b1 = np.array([1,1])
print("Ax = b with A = ", A, " and b1= ", b1, "\n")
print("x = ", np.linalg.solve(A,b1), "\n------------\n")
# or
print('Solve Ax=b, b=(1,0)\n', mtrx.linalg.solve(A, mtrx.matrix('1;0') ) )

Ax = b with A =  [[1. 0.]
 [0. 1.]]  and b1=  [1 1] 

x =  [1. 1.] 
------------

Solve Ax=b, b=(1,0)
 [[1.]
 [0.]]
